### ISSUE TITLE
is there a way to include, not just exclude?

### ISSUE THREAD

**Issue by davidparker** [tonerdo/coverlet#103]
I have added a test project,  however I get no coverage as I reference my project as VSTS Nuget to make build just way less complicated,  However I want cover to cover the actual project.

I.E

Main folder
        Web Project
         Extensions project
        Test Extensions Project  ( references extensions on nuget, so test project works on VSTS )
         
Ideally    want to run test but say  -->   this is the codes project our covering ../ExtensionsProject/Extensionsproject.csproj

Is this possible?

many thanks

**Comment by tonerdo** [comment]
Hi @davidparker currently all assemblies are included by default. I'm still considering a possible include feature in the future but there are no concrete plans

**Comment by davidparker** [comment]
Okay thanks for the response.   No problem.   Think im better of reverting
the nuget idea anyway   Thanks

**Comment by StephenMP** [comment]
@davidparker 
Your NuGet package idea doesn't make the build process less complicated, it actually makes it more complicated. How are you testing the latest version of the code in your build process? Having a NuGet package that has to get built first before having tests ran on it is backwards.

It's less complicated to have your source code project and a test project exist in the same solution. The test project references your source code project via a project reference in the same solution. Coverlet (and every other code coverage tool) works perfectly in that setup.

This also allows you to run your tests against the latest code without having to build the NuGet package first.

The build process is very simple at that point. I like to use the .NET Core Tasks in VSTS for .NET Core projects and run the `restore`, `test`, `pack`, and `nuget push` commands to accomplish a simple build process.

At this point, it would probably be good to close this issue since Coverlet already functions as expected for the proper setup.
