### ISSUE TITLE
MergeWith when multiple tagret frameworks

### ISSUE THREAD

**Issue by rodchenkov** [tonerdo/coverlet#1298]
Hi, just go issue when test and collect code coverage for project that has multiple frameworks.

`<TargetFrameworks>netcoreapp3.1;net5.0</TargetFrameworks>`

`
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: '**/*[Tt]ests/*.csproj'
    arguments: --configuration ${{ parameters.buildConfiguration }}
      --collect:"XPlat Code Coverage"
      --settings $(System.DefaultWorkingDirectory)/${{ parameters.codeCoverageSettingsFullPath }}
      -p:CollectCoverage=true
      -p:CoverletOutputFormat=json%2ccobertura
      -p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/
      -p:MergeWith=$(Build.SourcesDirectory)/TestResults/Coverage/coverage.json
    publishTestResults: true

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage reports'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/TestResults/Coverage/coverage*.cobertura.xml'
`

`
Calculating coverage result...
  Generating report '/home/vsts/work/1/s/TestResults/Coverage/coverage.netcoreapp3.1.json'
  Generating report '/home/vsts/work/1/s/TestResults/Coverage/coverage.netcoreapp3.1.cobertura.xml'

...

Calculating coverage result...
  Generating report '/home/vsts/work/1/s/TestResults/Coverage/coverage.net5.0.json'
  Generating report '/home/vsts/work/1/s/TestResults/Coverage/coverage.net5.0.cobertura.xml'
`

Here is my [project](https://github.com/GodelTech/GodelTech.Microservices.Security) with branch [feature/refactor](https://github.com/GodelTech/GodelTech.Microservices.Security/tree/feature/refactor/src/GodelTech.Microservices.Security).
Here is my [build.yml](https://github.com/GodelTech/AzureDevOps.Pipeline.Templates/blob/main/.NET%20Core/build.yml) 
Here is my build [results](https://dev.azure.com/godeltech/OpenSource/_build/results?buildId=3947&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=c3a82f0c-1888-5546-a492-c5d40199c25c)

What we can see here is that in `-p:MergeWith` we have `/coverage.json` file to merge, while collecting we have `coverage.netcoreapp3.1.json` so no merge occurs and each new test project overrides result of previous one because all of them store results in file with same name `coverage.netcoreapp3.1.json`.
Finally,  PublishCodeCoverageResults@1 task publishes it because summaryFileLocation is `/coverage*.cobertura.xml`

I see two issues here:
1. No merge of `coverage.<target framework>.json` in single `coverage.<target framework>.json`
2. No support to have multiple reports for each target framework e.g. netcoreapp3.1 and net5.0

Can you please help me with solving this issues?

P.S.
Thank you for all your hard work, really great project.

**Comment by petli** [comment]
Hi @rodchenkov, 

there's two ways of using coverlet with `dotnet test`, either `coverlet.collector` or `coverlet.msbuild`. E.g. https://github.com/GodelTech/GodelTech.Microservices.Security/blob/feature/refactor/test/GodelTech.Microservices.Security.Tests/GodelTech.Microservices.Security.Tests.csproj references both, and you also specify flags to activate both (`--collect:"XPlat Code Coverage"` and `-p:CollectCoverage=true`, respectively). From the output sample I think it's the latter that's running, but I'd recommend to only use one of them.

As to the question of merging reports: `coverlet.collector` cannot merge at all (because of the way the vstest framework works), and I'm not sure if `coverlet.msbuild` can merge across frameworks like you say.

An option that would work is to use https://danielpalme.github.io/ReportGenerator/ to merge the cobertura files. This has the benefit that you can use `coverlet.collector`, which doesn't suffer from a limitation in `vstest` that may cause `coverlet.msbuild` to not always produce results in CI environments (see https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#vstest-stops-process-execution-early)

A thing to be aware of with `coverlet.collector` is that the report files will be output in a subdirectory with a random GUID (this is managed by `vstest`, so coverlet cannot do much about it). Your CI build step running ReportGenerator will need to use a glob pattern to pick up report files from all the subdirectories.

**Comment by rodchenkov** [comment]
Hi @petli and thanks a lot for your help!
Now we are using just `coverlet.collector`, also merging with https://danielpalme.github.io/ReportGenerator/ works good.

Have only one question left and hope you can suggest something: how to solve multiple framework perorts `<TargetFrameworks>netcoreapp3.1;net5.0</TargetFrameworks>`? I mean to have one report for `netcoreapp3.1` and one for `net5.0`. Maybe you have any suggestions? Or maybe it is not even necessary to implement?

Thanks and have a nice day!

**Comment by petli** [comment]
> Have only one question left and hope you can suggest something: how to solve multiple framework perorts `<TargetFrameworks>netcoreapp3.1;net5.0</TargetFrameworks>`? I mean to have one report for `netcoreapp3.1` and one for `net5.0`. Maybe you have any suggestions? Or maybe it is not even necessary to implement?

Have you tried having multiple ReportGenerator build steps, one to produce the unified report and then two for the respective frameworks? A possible issue with this is #1276, as currently there's no way to identify the framework in the report file name and that would somehow have to be correlated from the test run output. There's a draft solution for this in #1299, however.
