### ISSUE TITLE
Index was out of range on /p:CoverletOutputFormat=\"cobertura,opencover\"

### ISSUE THREAD

**Issue by elvirdolic** [tonerdo/coverlet#135]
By providing multiple outputformats we get this error

dotnet test myProject.csproj --no-build --configuration release --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=\"cobertura,opencover\" /p:CoverletOutputDirectory=C:\temp\coverage --results-directory C:\temp

\coverlet.msbuild.targets(23,5): error : Index was out of range. Must be non-negative and less than the size of the collection. [C:\git\MyProject.Tests\MyProject.Tests.csproj]
C:\Users\xxx\.nuget\packages\coverlet.msbuild\2.0.1\build\netstandard2.0\coverlet.msbuild.targets(23,5): error : Parameter name: index [C:\git\MyProject.Tests\MyProject.Tests.csproj]

**Comment by tonerdo** [comment]
Woah, this is a first. Will take a look, shouldn't be too hard to fix

**Comment by andre-castro-garcia** [comment]
I have updated to the last version from Nuget (v2.0.1) and cannot reproduce this error in my tests.
I have executed the following command and both files are generate in folder:

`dotnet test test/ducktales.tests/ducktales.tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=\"cobertura,opencover\" /p:CoverletOutputDirectory=coverage /p:Exclude="[NUnit3.*]*"`
  
> Calculating coverage result...
>   Generating report 'coverage\coverage.cobertura.xml'
>   Generating report 'coverage\coverage.opencover.xml'

My repo url:
https://bitbucket.org/andre-castro-garcia/ducktales 
(I use the bitbucket because a native integration with bitbucket pipelines and sonarcloud)

@elvirdolic you can shared your repository or code snippet from your test project?

Andre Garcia

**Comment by elvirdolic** [comment]
By using this /p:CoverletOutputFormat=\"cobertura,opencover\" it does work. But somehow on VSTS this escaping doesn't work correctly. Thx for your support!!
