### ISSUE TITLE
Spurious 'Unable to read beyond end of stream' in CI while collecting results

### ISSUE THREAD

**Issue by Cyberboss** [tonerdo/coverlet#210]
https://travis-ci.org/tgstation/tgstation-server/jobs/438449753#L1156

Not sure what causes this it rarely happens and seemingly at random. Latest coverlet.console

**Comment by ppumkin** [comment]
Could it be that the files are cleaned up before Coverlet finishes doing its thing.

That error usually occurs when the StreamReader opens a file, it has its Length in memory then starts to stream the data... but its either 0, in very rare occasion in processes of being deleted.

For the Length to be more the length of the file is not possible unless it got modified as mentioned.

Because of this "randomness" it seems like a race condition somewhere.

**Comment by pedrofmanuel-sky** [comment]
I'm also facing this, but **consistently**, when dealing with a huge number of testcases (~17k), i.e. in our nightly builds (where more complete testing is done).

In regular use cases, I don't see this happening.


My use case: 
I'm calling coverlet, in **dotnet test** (via cake's DotNetCoreTest)

Error Line:
```[16:34:51] :     [Step 2/3] C:\Users\SVC-SS-BUILDER\.nuget\packages\coverlet.msbuild\2.3.1\build\netstandard2.0\coverlet.msbuild.targets(27,5): error : Unable to read beyond the end of the stream. 
```

More Detailed:
```
[16:34:51] :     [Step 2/3] Results File: D:\tc_ba2\510a05667bb2cb9a\test\DynamicPricing.Application.Nightly.Tests\TestResults\TestResults.trx
[16:34:51] :     [Step 2/3] 
[16:34:51] :     [Step 2/3] Total tests: 17071. Passed: 17071. Failed: 0. Skipped: 0.
[16:34:51] :     [Step 2/3] Test Run Successful.
[16:34:51] :     [Step 2/3] Test execution time: 26.1204 Minutes
[16:34:51]i:     [Step 2/3] TRX (1s)
[16:34:51] :     [Step 2/3] 
[16:34:51] :     [Step 2/3] Calculating coverage result...
[16:34:51] :     [Step 2/3] C:\Users\SVC-SS-BUILDER\.nuget\packages\coverlet.msbuild\2.3.1\build\netstandard2.0\coverlet.msbuild.targets(27,5): error : Unable to read beyond the end of the stream. [D:\tc_ba2\510a05667bb2cb9a\test\DynamicPricing.Application.Nightly.Tests\DynamicPricing.Application.Nightly.Tests.csproj]
[16:34:51]E:     [Step 2/3] An error occurred when executing task 'RunTests'.
[16:34:52]E:     [Step 2/3] Error message is logged
[16:34:51]E:     [Step 2/3] Error: System.AggregateException: One or more errors occurred. ---> Cake.Core.CakeException: .NET Core CLI: Process returned an error (exit code 1).
[16:34:51]E:     [Step 2/3]    at Cake.Core.Tooling.Tool`1.ProcessExitCode(Int32 exitCode)
[16:34:51]E:     [Step 2/3]    at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction)
[16:34:51]E:     [Step 2/3]    at Cake.Common.Tools.DotNetCore.Test.DotNetCoreTester.Test(String project, DotNetCoreTestSettings settings)
[16:34:51]E:     [Step 2/3]    at Submission#0.DotNetCoreTest(String project, DotNetCoreTestSettings settings)
[16:34:51]E:     [Step 2/3]    at Submission#0.<<Initialize>>b__0_27(String configuration, String provider, Tuple`2 connectionInfo, Boolean nightly, Boolean coverage)
[16:34:51]E:     [Step 2/3]    at Submission#0.<<Initialize>>b__0_26()
```

**Comment by ppumkin** [comment]
Yea it looks like coverlet is trying to open the file.. and its not there any more.
Again the common thing here is a CI pipeline.
Can you run this locally on your machine using dotnet test iwth coverlet?

**Comment by ppumkin** [comment]
So as I thought it is a CI related issue. Its not the build or coverlet problem it is that CI starts to cleanup too quickly.
Please tell us more about how your CI is setup, which platform etc. 

The next step of problem elimination is to manually run it on the CI Agent.

If it is AzureDevops can you should be able to get console access to your build agent and try and run the pipeline commands manually. See if it breaks the same way. If it does that means its an environment problem but I seriously doubt that. 

To Consider:

I think when the pipeline is executing one after the other.. there is a cleanup operation that is happening. Please check for any options like that and try and do cleanup at the end.. or, on first step do a clean sources and then make sure there are no other cleanup options tagged

Let us know what you find please.

**Comment by Cyberboss** [comment]
A potential workaround is to invoke bash and `sync` after

i.e.
```sh
$HOME/.dotnet/tools/coverlet bin/$CONFIG/netcoreapp2.1/Tgstation.Server.Api.Tests.dll --target "bash" --targetargs "-c 'dotnet test -c $CONFIG --no-build && sync'" --format opencover --output "../../TestResults/api.xml" --include "[Tgstation.Server*]*" --exclude "[Tgstation.Server.Api.Tests*]*"
```

**Comment by Cyberboss** [comment]
Disregard, it still errored out

**Comment by pedrofmanuel-sky** [comment]
I have the "feeling" that this has to do with some async (write) operation of some results, and when coverlet tries to read the output of it (it has not finished yet).

but this is just a guess...

**Comment by leppie** [comment]
Getting this too on AppVeyor lately (last 2 days). Nothing has changed on our side.

**Comment by tonerdo** [comment]
> Not sure what causes this it rarely happens and seemingly at random. Latest coverlet.console

Out of curiosity is everyone having this problem using `coverlet.console`?

**Comment by Cyberboss** [comment]
That is what I'm using

**Comment by leppie** [comment]
> > Not sure what causes this it rarely happens and seemingly at random. Latest coverlet.console
> 
> Out of curiosity is everyone having this problem using `coverlet.console`?

I am using `coverlet.msbuild` and just calling `dotnet test /p:CollectCoverage=true` on a per project basis in AppVeyor.

**Comment by pedrofmanuel-sky** [comment]
" just calling dotnet test /p:CollectCoverage=true on a per project basis"

Same here. Env: Windows + Teamcity + cake build script (which calls that, then).

**Comment by tonerdo** [comment]
Quick follow up question, does this only happen on a CI server? Anyone experienced it locally?

**Comment by Cyberboss** [comment]
I ran my tests with coverlet in a socket container for a few hours but
never got the error

**Comment by Cyberboss** [comment]
Docker*

**Comment by WiredUK** [comment]
Just wanted to add my support to this issue. We also have intermittent failures on our Azure DevOps pipeline. Here's a snippet from the last failure:

```
2018-11-08T17:03:48.4568642Z Results File: D:\agents\5\_work\_temp\SVC_TFSBuild_NCL-S-BUILD03_2018-11-08_17_03_47.trx
2018-11-08T17:03:48.4569469Z 
2018-11-08T17:03:48.4572151Z Total tests: 14. Passed: 14. Failed: 0. Skipped: 0.
2018-11-08T17:03:48.4572637Z Test Run Successful.
2018-11-08T17:03:48.4576890Z Test execution time: 12.9343 Seconds
2018-11-08T17:03:48.5061451Z 
2018-11-08T17:03:48.5062641Z Calculating coverage result...
2018-11-08T17:03:49.0712122Z D:\.nuget\packages\coverlet.msbuild\2.3.1\build\netstandard2.0\coverlet.msbuild.targets(27,5): error : Unable to read beyond the end of the stream. [D:\agents\5\_work\58\s\test\aaa.bbb.ccc.Unit.Tests\aaa.bbb.ccc.Unit.Tests.csproj]
```

**Comment by WiredUK** [comment]
I've started doing some testing on this one. Have a custom version of coverlet with a bunch of extra logging to hopefully extract exactly where and why this is exploding. It's quite tedious though as a CI build needs to run and the hamsters in our build server are very tired. Will update when I get some more info...

**Comment by ppumkin** [comment]
I sporadically get wierd things like this in CI on Azure. One thingin particular we still use a legaly FTP upload after the build completes for WbJobs. If I have clean up set on source. The FTP uplaod fails a lot. Dont know why because the cleanup is first and not after build. Very odd behavior.

As I mentioned before.. I know that error from working with files. It basically means the file has been deleted while trying to read it. (usually caused by some kind of race condition within ticks of cpu cyles) 

That log is cool.. but it would be cooler if you knew what file it is trying to read. I suppose Coverlet is trying to instrument the DLL then all of a sudden it disappears...

**Comment by WiredUK** [comment]
@ppumkin Yeah, I'm going to dig a little further now I know which part of the app to instrument.

**Comment by WiredUK** [comment]
@ppumkin Regarding your edit, the error could also be here:

https://github.com/tonerdo/coverlet/blob/7ede9d7cba383fea9709cee4d380c0de27b58b42/src/coverlet.core/Coverage.cs#L190

**Comment by ppumkin** [comment]
Yes, true. That is why I wrote its difficult to understand the code because is has a few levels of embedded loops and its reading 4 unsigned bytes each time from `result.HitsFilePath,` 
What is in that file? Some kind of temporary file. If it it is temporary maybe that is the problem on the CI builds, lack of permissions to access the file? it gets cleaned up after build runs? 

What is the file?

**Comment by pedrofmanuel-sky** [comment]
> yes! Temp directory! I bet you something on AZ (or other CI apparently like Travis) is cleaning up the temp after BUILD completes

The thing is, I'm running "dotnet test /p:CollectCoverage=true"  (and the problem existed) and coverlet runs within the test. therefore no "external" clean up should be happening meanwhile

**Comment by Cyberboss** [comment]
On Windows, there's some ways to change the tempdir location: https://stackoverflow.com/a/2365338/3976486.

I wonder how well mounting /tmp to a temp file would work on Linux

**Comment by ppumkin** [comment]
If the file exists and there is data inside it... maybe what the assumption of what was supposed to be in there is not always true for some reason.. and its trying to read the file beyond its capacity.

So it probably is a bug caused by assumption but again, this code should probably get patched up with some error trapping. I can fork this and put somethings if any body is interested in somehow using that patched version.. to atleast try and figure out the problem.

**Comment by WiredUK** [comment]
@ppumkin Well that's what my patched version is doing here, I'm spamming the log with all this data so I can understand exactly what is going on.

For reference, we are telling Azure DevOps to use the temp folder, that may be our problem. Our command line looks something like this:

```
dotnet test --no-build <path-to-project> -l trx -r $(Agent.TempDirectory) /p:CollectCoverage=true
```

**Comment by ppumkin** [comment]
Well we have identified the region of code that is causing the problem. 

I would suggest putting a few try catches around there and doing some more Verbose logging.

- Like capturing the size of the file before the first Int32 thing, 
- trying to capture data as the loops progress. 
- when an exception occurs capture the state of things at that point. Then you may be able to spot a logical problem or something else. Like try and see if the file still exists at point of exception try catch. things like that.

Unfortunately, that is the pain of working with files.

**Comment by WiredUK** [comment]
I'm definitely going to put in a PR which will show a better error message when the file is missing or empty, but that doesn't solve the base problem itself unfortunately.

**Comment by ppumkin** [comment]
No it does not solve the problem but it will help identify it correctly. 
The solution may be one of these 

> I think there needs to be a way to set the location of this file . (env var? settings.json?)
> It should check if the file exists if not then throw a proper message with the filepath
> Possibility to not use the file at all?

**Comment by pedrofmanuel-sky** [comment]
do we know who/what writes that file ? 
who/what is responsible for writing it, and for deleting it?

**Comment by WiredUK** [comment]
>I think there needs to be a way to set the location of this file . (env var? settings.json?)

You can do this, use the `-r <some-dir>` parameter

>It should check if the file exists if not then throw a proper message with the filepath

Yup, that's what I'll PR

>Possibility to not use the file at all?

Don't think this is possible. Those files are built by a completely different process.

**Comment by ppumkin** [comment]
I think it is used during instrumentation.  Probably some events/delegates that write some specific 4 byte wide data that Coverlet is then trying to read out in 4bytes at a time. 

Its not pretty... but it seems to have been done out of necessity

**Comment by Cyberboss** [comment]
Changing the directory from `Path.GetTempPath()` to something localized did not fix it, sadly.

![image](https://user-images.githubusercontent.com/8171642/48495545-3adbe880-e7fe-11e8-9681-b2e1621975e6.png)

https://travis-ci.org/tgstation/tgstation-server/jobs/455055580#L2872

**Comment by WiredUK** [comment]
OK I have new info. The file exists but is zero bytes. That just confuses me even more :/

**Comment by ppumkin** [comment]
Cool. 
So there is a problem at the point where something is trying to write to the file. It is looking more like a permissions thing. It can create the file... but not write it ??

**Comment by WiredUK** [comment]
I doubt it's a permission thing:
1. It's the temp folder for the user which won't have peculiar perms
2. It works most of the time

I'm looking to see if I can instrument where the file is created now...

**Comment by ppumkin** [comment]
The hunt continues ... 🗡

**Comment by pedrofmanuel-sky** [comment]
Could it be the result file, for some excluded assembly / namespaces, which didn't had any hits ?

**Comment by ppumkin** [comment]
That is good point... but the fact that it works sometimes without changing the code means, no.

**Comment by pedrofmanuel-sky** [comment]
if the tests are in fact predictable, and always pass on the same spots I would agree with you :) if not, then there's the possibility ;)

**Comment by WiredUK** [comment]
The fact they work sometimes means it's almost certainly nothing to do with excluded parts.

**Comment by pedrofmanuel-sky** [comment]
I'm just saying, if there's some dynamic execution, which stimulates different parts of the code, during the tests, then the situation could happen.

(but I do not know the tests / code behind it).

**Comment by pedrofmanuel-sky** [comment]
but of course, this is a very wild, wild guess.. :)

**Comment by Cyberboss** [comment]
I can confirm the file is zero bytes when failing: 

https://travis-ci.org/tgstation/tgstation-server/jobs/455073759#L1731

But, what's weird is I added checks for the program to die after it created the backup files if it was zero bytes and they never triggered.

https://github.com/Cyberboss/coverlet/commit/4baaea7709ec7ad1e7e13cf3a774869c98a39e16#diff-8b69d76eab513f470ef1ee9f7d7306daR46

**Comment by Cyberboss** [comment]
Actually, I didn't notice this before, but, there's a second implementation of `InstrumentationHelper.GetBackupPath()` here: https://github.com/tonerdo/coverlet/blob/master/src/coverlet.core/Instrumentation/Instrumenter.cs#L45 I'm gonna try messing with that too

**Comment by Cyberboss** [comment]
OK, so here's some more interesting stuff.

I made some modifications to the ModuleTrackerTemplate: https://github.com/tonerdo/coverlet/compare/master...Cyberboss:Testing#diff-164040e68c2b496a18449c2363998152R96

Now here's a failing build: https://travis-ci.org/tgstation/tgstation-server/jobs/455107315#L2630

It seems the process (or thread that runs that code at least) is being killed while `UnloadModule` is running, sometime after the `open` syscall. Compared to the other times where something is always written. This would explain why the file is zero bytes.

Now as for WHY the process is dying right then and there I have no idea. No exceptions are being thrown as far as I can tell (at least, nothing that can be caught with `catch (Exception e)`). It just seems to open the file and inexplicably die

**Comment by Cyberboss** [comment]
Ahh, I think it's a simple timeout the handler is hitting: https://stackoverflow.com/a/12341932/3976486

```
The total execution time of all ProcessExit event handlers is limited, just as the total execution time of all finalizers is limited at process shutdown. The default is two seconds.
```

**Comment by Cyberboss** [comment]
Travis CI is constantly under load, so I don't doubt it.

**Comment by petli** [comment]
A way to avoid to do a lot of work in ProcessExit might be to use a memory mapped file to keep track of hit counts, which would be pretty easy to implement after #181. Instead of allocating an int[] a memory mapped file the size of HitCandidates.Count * 4 would be allocated, and each hit increment a counter at HitIndex * 4.  This way there's no data to write to disk at the end of the test.

It shouldn't be a significant performance hit to use the memory mapped APIs instead of incrementing an int array directly, but that must be verified. It may not be necessary to use file-backed memory maps at all, and just use them as a shared memory area between the coverlet process and the test process.

To avoid locking threads on each others there would have to be one file per thread (much like there's one array per thread in #181), and Coverage.CalculateCoverage() would have to read all those files and tally them.

**Comment by ppumkin** [comment]
Is this a use case for the new Span<T> maybe? I never used it but listening to some conferences it sounds like that is what it could be used for? 

Any way, anything other than file system writes is going to be better..

**Comment by ElephantsGerald** [comment]
I can also confirm that this starts to become a problem on a CI server under load.

**Comment by Marachkouski** [comment]
We also have such problem in our build environment.

**Comment by codemzs** [comment]
Do people know if using an older nuget resolves this issue?

**Comment by codemzs** [comment]
@pjanotti With your check-in made at #181 there may be a race condition [here](https://github.com/tonerdo/coverlet/blob/54108b6f1e6fdf2afb51b80d6da55f610ee99456/src/coverlet.core/Coverage.cs#L206) where HitsFilePath exists but its contents are empty. Can you think of something? I'm hitting this issue intermittently and did very brief analysis to narrow the issue down.

**Comment by sharwell** [comment]
I narrowed this down with @codemzs today. The failure occurs when the hit file is truncated due to process termination while writing the file. After that point, subsequent loads of the file for coverage gathering fail because the file is either empty or contains fewer entries than claimed. I'm planning to address two parts of this and send a pull request:

1. Improve write performance using memory mapped files, allowing the final flush to disk to occur after the process closes.
2. During reads, handle files that are too short by assuming the rest of the data is zero-filled.

There was some mention above of possible timeouts. I'm not planning to address this part specifically, but if the allowed data flush duration can be extended then it would likely round out the situation for great overall reliability.

**Comment by codemzs** [comment]
Can we please get #276 in to address the issue and have a new nuget? @Cyberboss @tonerdo @petli

**Comment by tonerdo** [comment]
@Cyberboss @codemzs New NuGet releases with the proposed fixed have been released

**Comment by petli** [comment]
@ViktorHofer Do you think named pipes be as fast as stdout?  The pipe name could be passed into the instrumented code via ModuleTrackerTemplate much like the mmap name.

**Comment by sharwell** [comment]
I'm starting to think the cause of this issue lies in the test runner itself, as opposed to the CLR. However, I haven't been able to pinpoint the sequence in the vstest runner that leads to the forced termination of the test process.

**Comment by ViktorHofer** [comment]
Correct the shutdown is triggered by vstest. This can be easily tested with the following code. Happens with both mstest and xunit which proves that its not the runner itself but the testing framework (vstest) who is responsible for stopping the execution early.

```
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Diagnostics;
using System.Threading.Tasks;

namespace dotnettest
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void Test1()
        {
            AppDomain.CurrentDomain.ProcessExit += CurrentDomain_ProcessExit;
        }

        private void CurrentDomain_ProcessExit(object sender, EventArgs e)
        {
            System.IO.File.WriteAllText("abc.txt", "start");
            Task.Delay(10000).Wait();
            System.IO.File.WriteAllText("abc.txt", "end");
        }
    }
}
```

Related code paths in vstest:
https://github.com/Microsoft/vstest/blob/7b6248203164f8ea821f6795632bd22e0b69afb0/src/Microsoft.TestPlatform.CoreUtilities/Utilities/JobQueue.cs

VSTest which is triggered by `dotnet test` is responsible I'll try to gather more information. 

As a workaround you can use coverlet.console instead of coverlet.msbuild.

**Comment by MarcoRossignoli** [comment]
Close thank's to new collectors https://github.com/tonerdo/coverlet#requirements
