### ISSUE TITLE
Version 2.5.0 

### ISSUE THREAD

**Issue by jherby2k** [tonerdo/coverlet#272]
I upgraded my projects to v2.5.0, and now CI is failing on my .NET Framework 4.7.1 tests (they still pass under .net Core 2.1).

Could not load file or assembly 'System.Runtime.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.

Going to have to downgrade for now.

**Comment by tonerdo** [comment]
I updated the core library to use `netcoreapp2.0` instead of `netstandard` because I needed to add support for a particular area. That's probably the problem

**Comment by yhvicey** [comment]
Facing same error here. Workaround it by downgrade to 2.4.0.

**Comment by yhvicey** [comment]
Maybe `coverlet.msbuild` and `coverlet.msbuild.tasks` can be merged and published using [the new way](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#nuget-metadata-properties), instead of manully specify which dlls should be packed. With `dotnet build` and `<GeneratePackageOnBuild>true</GeneratePackageOnBuild>`, MSBuild will help you to handle the dependencies. I'll try to do a POC.

**Comment by jherby2k** [comment]
Confirmed fixed with 2.5.1. Thanks!
