### ISSUE TITLE
Exception filters appear on the wrong line 

### ISSUE THREAD

**Issue by hughbe** [tonerdo/coverlet#278]
Steps:
```
dotnet tool install --global dotnet-reportgenerator-globaltool
git clone https://github.com/hughbe/wpf
cd wpf
git checkout coverlet
dotnet test ./src/Microsoft.DotNet.Wpf/test/System.Xaml /P:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./coverage.xml /P:ExcludeByAttribute=ExcludeFromCodeCoverageAttribute
reportgenerator -reports:./coverage.xml -targetdir:./coverage
```

## Expected

- Exception filters coverage is on the right line

## Actual

- Exception filters are on the wrong line

See for example L1349 of the coverage for XamlSchemaContext.cs
![image](https://user-images.githubusercontent.com/1275900/50385591-195cff00-06d0-11e9-84c2-782911393dd1.png)

**Comment by pape77** [comment]
I have the exact same issue
@tonerdo any ideas?

**Comment by pape77** [comment]
Actually in my case i get branches in both lines

**Comment by pape77** [comment]
![image](https://user-images.githubusercontent.com/7718578/51608500-efd60400-1f17-11e9-824d-3066976666f8.png)

In my case it looks like this

**Comment by pape77** [comment]
Any ideas on this? :/

**Comment by MarcoRossignoli** [comment]
Sorry @pape77 it's been a busy period for me, but I didn't forget!I'll try to tackle it next weeks!

**Comment by pape77** [comment]
Thanks @MarcoRossignoli ;)

**Comment by MarcoRossignoli** [comment]
@pape77 @hughbe I found the issue, symbol helper doesn't work well with branch inside filter block, [`FindClosestInstructionWithSequencePoint`](https://github.com/tonerdo/coverlet/blob/master/src/coverlet.core/Symbols/CecilSymbolHelper.cs#L251) tries to find right sequence point line but fails.
My idea is to skip branch inside filter like finally, because filter could be and/or of conditions and for purpose of coverage we need to know if we cover catch code or no not if we skipped filter block, filter block doesn't have "code to cover" only conditions to evaluate(call to methods or condition/vars to evaluate).
Preview https://github.com/tonerdo/coverlet/compare/master...MarcoRossignoli:exceptionfilter

**Comment by pape77** [comment]
@MarcoRossignoli first, thanks! Great that you once more found the issue and are attempting to fix it 💃 

I think I agree with skipping branches in filter, since sometimes you just cannot force each type of exception that you may have as an `or` in your filter , while testing, i think.
I'll discuss this with some colleagues to see what they think also. But is it possible to still take it into account if, say, it's said "if you cannot fake it through a test, it's not really possible to make it happen in real code", as i imagine that being an argument to be raised :P 

Last minor thing, in your test, i think you can use Single instead of First :)

**Comment by pape77** [comment]
@MarcoRossignoli I stole your code and used it on the one project that I have using this so far. Works :)

**Comment by MarcoRossignoli** [comment]
> @MarcoRossignoli I stole your code and used it on the one project that I have using this so far. Works :)

Can you attach sample image?I'll open a draft PR maybe we'll meet there for "tests".

**Comment by pape77** [comment]
@MarcoRossignoli You mean like this? (It's the same code of my previous image, now fixed)
![screen shot 2019-02-18 at 12 09 09](https://user-images.githubusercontent.com/7718578/52947144-2f0c3f00-3376-11e9-851b-d46195c0a895.png)

What I ment for tests was this (this is how i have it in my fork):
```
 // arrange
            var type = _module.Types.Single(x => x.FullName == typeof(ExceptionFilter).FullName);
            var method = type.Methods.Single(x => x.FullName.Contains($"::{nameof(ExceptionFilter.Test)}"));
```

So using `Single` istead of `First` for `_module.Types/Methods`

Cheers!
