### ISSUE TITLE
Consolidate infra artifacts under repo root or eng folder

### ISSUE THREAD

**Issue by MarcoRossignoli** [tonerdo/coverlet#435]
At the end of all "refactor" of "builds" we should decide if move all "files"(yaml and scripts) under eng[ineering] folder or simply in root repo.

cc: @tonerdo @AArnott

**Comment by AArnott** [comment]
I'm a fan of keeping relatively few files in the root of the repo. In fact I keep a `src` folder in each of my repos where *all* solution-related assets reside. I leave the root of the repo for READMEs and other common interest files. I won't push that too hard here though, since I might be moving `version.json` and `global.json` back to the root of my repos for practical convenience reasons.

I usually keep my `azure-pipelines.yml` file in the root, since that's where Azure Pipelines will find it automatically. Then the templates that it imports come from an `azure-pipelines` folder under the root.
If you have a build script, that's probably most convenient/discoverable if left in the root of the repo as well, but if it brought in many more files, hiding those in some sub-folder sounds good to me.
