### ISSUE TITLE
No runsettings property for single code coverage file for multiple test projects

### ISSUE THREAD

**Issue by unrealsoul007** [tonerdo/coverlet#740]
Using coverlet.collector or coverlet.msbuild, I don't see an option to get the code coverage from multiple dotnet core test projects in a single output file. I know coverlet.console can do that but for our scenario coverlet.console doesn't fit. 
Is there already a setting that can be specified so that a single coverlet.cobertura.xml file is generated in the TestResults folder?

**Comment by MarcoRossignoli** [comment]
for msbuild is present take a look at our example https://github.com/tonerdo/coverlet/tree/master/Documentation/Examples/MSBuild/MergeWith

BTW msbuild has got some know issue...https://github.com/tonerdo/coverlet/blob/master/Documentation/KnowIssues.md#know-issues

If you hit these issues you need to use collectors that at the moment doesn't have a way to merge results, because we're constrained by vstest platform.
We're working on it https://github.com/tonerdo/coverlet/issues/683#issuecomment-578428855 and try to provide an external way to merge result.

BTW there are some report system that merge more report with no problem like reportgenerator https://danielpalme.github.io/ReportGenerator/

IMO merging report should be a feat of "reporting tool" not of coverage tool, dotnet run project not solution(we don't compile solution) so we have an output coverage for every test project ran.

**Comment by unrealsoul007** [comment]
I tried using the coverlet.msbuild with the MergeWith option and the final coverlet.cobertura.xml file only contains results from the last test project it ran. I did not see any intermediate coverage.json left behind. Here is the command that I am running:

`for testproj in $(find . -iname '*Test.csproj' -or -iname '*Tests.csproj')
do
    echo -e "Running test project $testproj"
    #dotnet test --logger trx --results-directory "$ROOTDIR/bin/TestResults" --collect:"XPlat Code Coverage" "$testproj"
    dotnet test "$testproj" /p:CollectCoverage=true  /p:CoverletOutput=."$ROOTDIR/bin/TestResults/CoverageResults/" /p:MergeWith="$ROOTDIR/bin/TestResults/CoverageResults/coverage.json" /p:CoverletOutputFormat="cobertura"
done`

I tried to run the sample project that you pointed me to in your previous comment using the following command:

`dotnet test XUnitTestProject1/XUnitTestProject1.csproj /p:CollectCoverage=true  /p:CoverletOutput=../CoverageResults/`

the output of this command shows:
````
Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
                                                                                                                                                                                                            
Test Run Successful.
Total tests: 1
     Passed: 1
 Total time: 2.9140 Seconds

Calculating coverage result...
  Generating report '../CoverageResults/coverage.json'

+---------------+------+--------+--------+
| Module        | Line | Branch | Method |
+---------------+------+--------+--------+
| ClassLibrary1 | 75%  | 100%   | 50%    |
+---------------+------+--------+--------+

+---------+------+--------+--------+
|         | Line | Branch | Method |
+---------+------+--------+--------+
| Total   | 75%  | 100%   | 50%    |
+---------+------+--------+--------+
| Average | 75%  | 100%   | 50%    |
+---------+------+--------+--------+
````

But there is no folder ../CoverageResults generated.

**Comment by unrealsoul007** [comment]
Thanks for pointing me to correct example for coverlet.msbuild. It works and I can finally have one unified coverage file. 
Report generator does merge for an html view but it doesn't generate a single coverage file. Maybe that can be a feature ask on ReportGenerator because it anyway analyses all the coverage files to generate the report.
