### ISSUE TITLE
Instrumenting ASP.NET Core Views.dll takes >20 minutes

### ISSUE THREAD

**Issue by nheath99** [tonerdo/coverlet#761]
On both Azure DevOps and GitHub Actions I am coming across the same issue. Since upgrading to ASP.NET Core 3.1, calling the following code takes over 20 minutes to execute, and will often cause the build to fail due to timeout:

````dotnet test --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude="[ActionsTest.Views.dll]*%2c[xunit.*]*"````

The Solution contains one ASP.NET Core 3.1 application, and a number of .Net Standard 2.0 class libraries. By running ````dotnet test```` on each project individually, it is only the ASP.Net Core project that takes so long (all the others take a reasonable length of time to complete, a few seconds to 1-2 minutes for a large one).

By setting the ````verbose```` flag, I can see that the line that takes to long is the second line (I've added the previous line to show the timestamp):

```
Mon, 16 Mar 2020 15:25:11 GMT
[coverlet] Instrumented module: 'D:\a\ActionsTest\ActionsTest\tests\ActionsTest.Test\bin\Debug\netcoreapp3.1\ActionsTest.dll'
Mon, 16 Mar 2020 15:49:44 GMT
[coverlet] Instrumented module: 'D:\a\ActionsTest\ActionsTest\tests\ActionsTest.Test\bin\Debug\netcoreapp3.1\ActionsTest.Views.dll'
```

It seems that
1. the Exclude parameter isn't excluding the ActionsTest.Views.dll assembly, and
2. Instrumenting *.Views.dll takes a huge amount of time

Please let me know if you need any more information.

**Comment by MarcoRossignoli** [comment]
Some notes/question:

1) If  the app is .net core app you should use https://github.com/tonerdo/coverlet#vstest-integration-preferred-due-to-known-issue
2) Which version are you using?Because test dll should be excluded by design so it's strange that are in instrumented list https://github.com/tonerdo/coverlet/blob/master/Documentation/VSTestIntegration.md#coverlet-options-supported-by-vstest-integration check `IncludeTestAssembly` parameter(same parameter works for the other type of integration msbuild/.net tool)
3) can you try with `/p:Exclude="[ActionsTest.Views.*]*%2c[xunit.*]*"`

**Comment by nheath99** [comment]
1. Ok I am using coverlet.collector now.
2. v1.2.0 (latest). I was using v2.8.0 (latest) of coverlet.msbuild
3. When I use `/p:Exclude="[ActionsTest.Views.*]*` with coverlet.collector I get a simple error with no explanation. When I use coverlet.collector without the `exclude` then it runs successfully, but hangs for 15 minutes saying `Starting test execution, please wait`. The next line is `A total of 1 test files matched the specified pattern`. The individual unit tests then run successfully in a few s.

**Comment by MarcoRossignoli** [comment]
> When I use /p:Exclude="[ActionsTest.Views.*]* with coverlet.collector I get a simple error with no explanation. 

Can you attach your error?

>  but hangs for 15 minutes saying Starting test execution, please wait. The next line is A total of 1 test files matched the specified pattern. The individual unit tests then run successfully in a few s.

The run with coverage will be always more slow, because coverlet instruments code injecting a call to register a hit(means I passed here) for every line and every branch, so if your test has got loops every one will run slowly because more code will be executed.
For instance take a look to this similar issue https://github.com/tonerdo/coverlet/issues/511#issuecomment-519446983 as you can see every `RecordSingleHit` is injected by coverlet. So there are some scenario where tests will be a lot slow.

**Comment by nheath99** [comment]
1. My mistake, it was a typo (I missed the final quote `"`)
2. Yes I was aware of this, I was just surprised that the length of time to cover a ASP.Net core 3.1 was significantly higher than before, and other .net core projects - I do not have many loops or particularly slow code, maybe I can have a look at this in the future.
3. Yes you are right, I get the expected coverage file at the end.

PS thank you for your work on this project, it's really appreciated 🙂 
PPS I hope the current situation in Italy improves soon! 🙏

**Comment by MarcoRossignoli** [comment]
> PS thank you for your work on this project, it's really appreciated 🙂

Thank's for patience and for using coverlet

> PPS I hope the current situation in Italy improves soon! 

Thank's we're fighting, we'll make it!
