### ISSUE TITLE
Is existence of sources necessary for coverlet?

### ISSUE THREAD

**Issue by jakubch1** [tonerdo/coverlet#782]
Coverlet instruments only binaries for which sources can be found on disk. Is this hard dependency? In some CI scenarios build is happening on 1 machine but tests execution on another machine where sources are not available. If sources existence is just used to filter not relevant binaries can we have some option to turn off this check?

**Comment by MarcoRossignoli** [comment]
> Coverlet instruments only binaries for which sources can be found on disk. Is this hard dependency?

Yep because when coverlet needs to save the mapping between the "candidate" hits and the sequnce point/branch in code 

https://github.com/tonerdo/coverlet/blob/4c1cdf9ee976a869d9a7c426749b600afa8899ea/src/coverlet.core/Instrumentation/Instrumenter.cs#L496-L558

> In some CI scenarios build is happening on 1 machine but tests execution on another machine where sources are not available. If sources existence is just used to filter not relevant binaries can we have some option to turn off this check?

In this scenario the source is needed only on build/instrument phase, after that the instrumented dll can be moved everywhere, but the "instrumentation result" must be saved somewhere, without that mapping we cannot know what hits(int[]) refers to.
Here we do the accounting of hits->sequence point(line) and branches https://github.com/tonerdo/coverlet/blob/master/src/coverlet.core/Coverage.cs#L353

**Comment by MarcoRossignoli** [comment]
cc: @tonerdo

**Comment by jakubch1** [comment]
Sequence point/branch stuff is coming from pdbs through Cecil  if I understand it correctly. We are using path to source file but we are not reading the source file. I can be wrong here. I think we can test it by removing all code from file before instrumentation. 
Does Cecil need source files?

**Comment by MarcoRossignoli** [comment]
> Sequence point/branch stuff is coming from pdbs through Cecil if I understand it correctly. We are using path to source file but we are not reading the source file

Yes correct we read file path and check if present in local https://github.com/tonerdo/coverlet/blob/master/src/coverlet.core/Helpers/InstrumentationHelper.cs#L122

> Does Cecil need source files?

No Cecil inspect and instrument IL and support portable pdb reading.

>  I think we can test it by removing all code from file before instrumentation.

Yes, we don't need sources on "test server" but only instrumented dll, if I understood well your question.

**Comment by MarcoRossignoli** [comment]
Maybe I wasn't clear, we don't need sources on "test server" so this workflow will work

1) Instrument dll
2) Send dll to a server and run `dotnet vstest`(I think we use it if we don't have csproj)
3) Running test send hits to server(thank's to instrumented dll, tracker will connect to server and send hits)
4) Server calculate coverage when it wants

**Comment by MarcoRossignoli** [comment]
@jakubch1 can we close this?

**Comment by jakubch1** [comment]
Yes. Closing it. I will check it.
